import type { Disposable, Result } from '../../contracts/src/index';

export interface TaskSpec { readonly id: string; readonly argv: readonly [string, ...string[]]; readonly cwd: string; readonly maxOutputBytes?: number; }
export interface TaskProcess extends Disposable { readonly exit: Promise<Result<{ readonly code: number | null; readonly signal: string | null }, TaskFailure>>; onStdout(listener: (bytes: Uint8Array) => void): Disposable; onStderr(listener: (bytes: Uint8Array) => void): Disposable; terminate(): Promise<void>; }
export interface TaskProcessFactory { spawn(spec: TaskSpec): Promise<Result<TaskProcess, TaskFailure>>; }
export interface TaskOutputSnapshot { readonly taskId: string; readonly stdout: string; readonly stderr: string; readonly bytes: number; readonly truncated: boolean; readonly state: 'idle' | 'running' | 'exited' | 'failed' | 'cancelled'; readonly exitCode: number | null; }
export type TaskFailure = { readonly kind: 'spawn' | 'failed' | 'cancelled' | 'output-limit' | 'disposed'; readonly message: string };

export class TaskController implements Disposable {
  readonly #factory: TaskProcessFactory; readonly #maxOutputBytes: number; #process: TaskProcess | undefined; #snapshot: TaskOutputSnapshot; #disposed = false; #out: Disposable[] = [];
  constructor(factory: TaskProcessFactory, maxOutputBytes = 1_048_576) { this.#factory = factory; this.#maxOutputBytes = Math.max(1024, Math.trunc(maxOutputBytes)); this.#snapshot = Object.freeze({ taskId: '', stdout: '', stderr: '', bytes: 0, truncated: false, state: 'idle', exitCode: null }); }
  get snapshot(): TaskOutputSnapshot { return this.#snapshot; }
  async start(spec: TaskSpec): Promise<Result<TaskOutputSnapshot, TaskFailure>> { if (this.#disposed) return { ok: false, error: { kind: 'disposed', message: 'task controller disposed' } }; await this.cancel(); const spawned = await this.#factory.spawn(spec); if (!spawned.ok) { this.#snapshot = Object.freeze({ ...this.#snapshot, taskId: spec.id, state: 'failed' }); return spawned; } this.#process = spawned.value; this.#snapshot = Object.freeze({ taskId: spec.id, stdout: '', stderr: '', bytes: 0, truncated: false, state: 'running', exitCode: null }); this.#out = [this.#process.onStdout((bytes) => this.append('stdout', bytes)), this.#process.onStderr((bytes) => this.append('stderr', bytes))]; void this.#process.exit.then((exit) => { if (!exit.ok) { this.#snapshot = Object.freeze({ ...this.#snapshot, state: 'failed' }); return; } this.#snapshot = Object.freeze({ ...this.#snapshot, state: exit.value.code === null ? 'cancelled' : 'exited', exitCode: exit.value.code }); }); return { ok: true, value: this.#snapshot }; }
  async cancel(): Promise<void> { const process = this.#process; if (process === undefined) return; this.#process = undefined; for (const subscription of this.#out) subscription.dispose(); this.#out = []; await process.terminate(); this.#snapshot = Object.freeze({ ...this.#snapshot, state: 'cancelled' }); process.dispose(); }
  private append(kind: 'stdout' | 'stderr', bytes: Uint8Array): void { if (this.#disposed || this.#snapshot.state !== 'running') return; const remaining = this.#maxOutputBytes - this.#snapshot.bytes; const accepted = bytes.slice(0, Math.max(0, remaining)); const text = new TextDecoder().decode(accepted); this.#snapshot = Object.freeze({ ...this.#snapshot, [kind]: `${this.#snapshot[kind]}${text}`, bytes: this.#snapshot.bytes + accepted.byteLength, truncated: accepted.byteLength !== bytes.byteLength }); }
  dispose(): void { if (this.#disposed) return; this.#disposed = true; void this.cancel(); }
}
