import assert from 'node:assert/strict';
import { execFileSync } from 'node:child_process';
import { existsSync, mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

const architecture = process.arch === 'arm64' ? 'aarch64' : process.arch === 'x64' ? 'x86_64' : undefined;
assert.notEqual(architecture, undefined, 'T036-LSP-ENABLE-HELIX-01 pinned Helix has a supported host binary');
const helix = join(import.meta.dir, '../../.artifacts/reference/helix/25.07.1/helix-25.07.1-' + architecture + '-linux/hx');
const helixMasterEditorDocs = join(import.meta.dir, '../../.artifacts/reference/helix/master/book/src/editor.md');
const helixMasterConfigurationDocs = join(import.meta.dir, '../../.artifacts/reference/helix/master/book/src/configuration.md');
const helixMasterCommandDocs = join(import.meta.dir, '../../.artifacts/reference/helix/master/book/src/generated/typable-cmd.md');
  assert.equal(existsSync(helix), true, 'T036-LSP-ENABLE-HELIX-01 pinned Helix binary exists');
assert.equal(existsSync(helixMasterEditorDocs), true, 'T036-STATUSLINE-CWD-HELIX-01 pinned Helix master editor docs exist');
assert.equal(existsSync(helixMasterConfigurationDocs), true, 'T036-LOADING-USER-HELIX-01 pinned Helix configuration docs exist');
assert.equal(existsSync(helixMasterCommandDocs), true, 'T036-CONFIG-OPEN-HELIX-01 pinned Helix master command docs exist');
assert.match(readFileSync(helixMasterCommandDocs, 'utf8'), /`:config-open`/u, 'T036-CONFIG-OPEN-HELIX-01 pinned Helix documents config-open');
assert.match(readFileSync(helixMasterCommandDocs, 'utf8'), /`:config-reload`/u, 'T036-CONFIG-RELOAD-HELIX-01 pinned Helix documents config-reload');
assert.match(readFileSync(helixMasterConfigurationDocs, 'utf8'), /USR1/u, 'T036-CONFIG-RELOAD-USR1-HELIX-01 pinned Helix documents USR1 config reload');
assert.match(readFileSync(helixMasterEditorDocs, 'utf8'), /\| `current-working-directory` \|/u, 'T036-STATUSLINE-CWD-HELIX-01 Helix master defines current-working-directory');
assert.match(readFileSync(helixMasterConfigurationDocs, 'utf8'), /config\.toml/u, 'T036-LOADING-USER-HELIX-01 pinned Helix documents the user config.toml contract');
const temporary = mkdtempSync('/tmp/xi-helix-lsp-enable-');
try {
  const fixture = join(temporary, 'helix-25.07.1.toml');
  writeFileSync(fixture, readFileSync(join(import.meta.dir, '../fixtures/config/helix-25.07.1.toml')));
  mkdirSync(join(temporary, '.helix'));
  writeFileSync(join(temporary, '.helix/config.toml'), '[editor]\nline-number = "relative"\n');
  assert.match(readFileSync(fixture, 'utf8'), /^scroll-lines = 3$/m, 'T036-SCROLL-LINES-HELIX-01 canonical fixture contains editor.scroll-lines');
  assert.match(readFileSync(fixture, 'utf8'), /^continue-comments = true$/m, 'T036-CONTINUE-COMMENTS-HELIX-01 canonical fixture contains editor.continue-comments');
  assert.match(readFileSync(fixture, 'utf8'), /^idle-timeout = 250$/m, 'T036-IDLE-TIMEOUT-HELIX-01 canonical fixture contains editor.idle-timeout');
  assert.match(readFileSync(fixture, 'utf8'), /^theme = "default"$/m, 'T036-THEME-ROOT-HELIX-01 canonical fixture contains root theme');
  assert.match(readFileSync(fixture, 'utf8'), /^mouse = true$/m, 'T036-MOUSE-HELIX-01 canonical fixture contains editor.mouse');
  assert.match(readFileSync(fixture, 'utf8'), /^line-number = "absolute"$/m, 'T036-LINE-NUMBER-HELIX-01 canonical fixture contains editor.line-number');
  assert.match(readFileSync(fixture, 'utf8'), /^separator = "│"$/m, 'T036-STATUSLINE-SEPARATOR-HELIX-01 canonical fixture contains editor.statusline.separator');
  assert.match(readFileSync(fixture, 'utf8'), /^mode\.normal = "NOR"$/m, 'T036-STATUSLINE-MODES-HELIX-01 canonical fixture contains editor.statusline.mode.normal');
  assert.match(readFileSync(fixture, 'utf8'), /^mode\.insert = "INS"$/m, 'T036-STATUSLINE-MODES-HELIX-01 canonical fixture contains editor.statusline.mode.insert');
  assert.match(readFileSync(fixture, 'utf8'), /^mode\.select = "SEL"$/m, 'T036-STATUSLINE-MODES-HELIX-01 canonical fixture contains editor.statusline.mode.select');
  assert.match(readFileSync(fixture, 'utf8'), /^diagnostics = \["warning", "error"\]$/m, 'T036-STATUSLINE-DIAGNOSTICS-HELIX-01 canonical fixture contains editor.statusline.diagnostics');
  assert.match(readFileSync(fixture, 'utf8'), /^workspace-diagnostics = \["warning", "error"\]$/m, 'T036-STATUSLINE-WORKSPACE-DIAGNOSTICS-HELIX-01 canonical fixture contains editor.statusline.workspace-diagnostics');
  assert.match(readFileSync(fixture, 'utf8'), /^min-width = 3$/m, 'T036-GUTTER-MIN-WIDTH-HELIX-01 canonical fixture contains editor.gutters.line-numbers.min-width');
  assert.match(readFileSync(fixture, 'utf8'), /^layout = \["diagnostics", "spacer", "line-numbers", "spacer", "diff", "code-action-hint"\]$/m, 'T036-GUTTERS-HELIX-01 canonical fixture contains the stable gutter layout');
  assert.match(readFileSync(fixture, 'utf8'), /^\[editor\.indent-guides\]$/m, 'T036-INDENT-GUIDES-HELIX-01 canonical fixture contains editor.indent-guides');
  assert.match(readFileSync(fixture, 'utf8'), /^render = false$/m, 'T036-INDENT-GUIDES-HELIX-01 canonical fixture contains indent-guide render');
  assert.match(readFileSync(fixture, 'utf8'), /^character = "│"$/m, 'T036-INDENT-GUIDES-HELIX-01 canonical fixture contains indent-guide character');
  assert.match(readFileSync(fixture, 'utf8'), /^skip-levels = 0$/m, 'T036-INDENT-GUIDES-HELIX-01 canonical fixture contains indent-guide skip-levels');
  assert.match(readFileSync(fixture, 'utf8'), /^\[editor\.whitespace\.render\]$/m, 'T036-WHITESPACE-HELIX-01 canonical fixture contains editor.whitespace.render');
  assert.match(readFileSync(fixture, 'utf8'), /^space = "none"$/m, 'T036-WHITESPACE-HELIX-01 canonical fixture contains whitespace space rendering');
  assert.match(readFileSync(fixture, 'utf8'), /^tab = "none"$/m, 'T036-WHITESPACE-HELIX-01 canonical fixture contains whitespace tab rendering');
  assert.match(readFileSync(fixture, 'utf8'), /^newline = "none"$/m, 'T036-WHITESPACE-HELIX-01 canonical fixture contains whitespace newline rendering');
  assert.match(readFileSync(fixture, 'utf8'), /^\[editor\.whitespace\.characters\]$/m, 'T036-WHITESPACE-HELIX-02 canonical fixture contains whitespace characters');
  assert.match(readFileSync(fixture, 'utf8'), /^space = "·"$/m, 'T036-WHITESPACE-HELIX-02 canonical fixture contains space character');
  assert.match(readFileSync(fixture, 'utf8'), /^nbsp = "⍽"$/m, 'T036-WHITESPACE-HELIX-02 canonical fixture contains nbsp character');
  assert.match(readFileSync(fixture, 'utf8'), /^nnbsp = "␣"$/m, 'T036-WHITESPACE-HELIX-02 canonical fixture contains nnbsp character');
  assert.match(readFileSync(fixture, 'utf8'), /^tab = "→"$/m, 'T036-WHITESPACE-HELIX-02 canonical fixture contains tab character');
  assert.match(readFileSync(fixture, 'utf8'), /^tabpad = "·"$/m, 'T036-WHITESPACE-HELIX-02 canonical fixture contains tabpad');
  assert.match(readFileSync(fixture, 'utf8'), /^newline = "⏎"$/m, 'T036-WHITESPACE-HELIX-02 canonical fixture contains newline character');
  assert.match(readFileSync(fixture, 'utf8'), /^\[editor\.smart-tab\]$/m, 'T036-SMART-TAB-HELIX-01 canonical fixture contains editor.smart-tab');
  assert.match(readFileSync(fixture, 'utf8'), /^enable = true$/m, 'T036-SMART-TAB-HELIX-01 canonical fixture contains smart-tab enable');
  assert.match(readFileSync(fixture, 'utf8'), /^supersede-menu = false$/m, 'T036-SMART-TAB-HELIX-01 canonical fixture contains smart-tab supersede-menu');
  assert.match(readFileSync(fixture, 'utf8'), /^\[editor\.auto-pairs\]$/m, 'T036-AUTO-PAIRS-HELIX-01 canonical fixture contains editor.auto-pairs');
  assert.match(readFileSync(fixture, 'utf8'), /^'\(' = '\)'$/m, 'T036-AUTO-PAIRS-HELIX-01 canonical fixture contains the standard parenthesis pair');
  assert.match(readFileSync(fixture, 'utf8'), /^'`' = '`'$/m, 'T036-AUTO-PAIRS-HELIX-01 canonical fixture contains the standard backtick pair');
  assert.match(readFileSync(fixture, 'utf8'), /^editor-config = true$/m, 'T036-EDITOR-CONFIG-HELIX-01 canonical fixture contains editor-config');
assert.match(readFileSync(helixMasterEditorDocs, 'utf8'), /#### `\[editor\.gutters\.diagnostics\]` Section/u, 'T036-GUTTERS-EMPTY-HELIX-01 pinned Helix documents the diagnostics gutter section');
assert.match(readFileSync(helixMasterEditorDocs, 'utf8'), /auto-pairs = false/u, 'T036-AUTO-PAIRS-BOOLEAN-HELIX-01 pinned Helix documents the boolean disable form');
assert.match(readFileSync(helixMasterEditorDocs, 'utf8'), /jump-label-alphabet/u, 'T036-JUMP-LABEL-HELIX-01 pinned Helix master documents jump-label-alphabet');
assert.match(readFileSync(helixMasterEditorDocs, 'utf8'), /`workspace-lsp-roots` \| Directories relative to the workspace root that are treated as LSP roots/u, 'T036-WORKSPACE-LSP-ROOTS-HELIX-02 pinned Helix documents relative workspace LSP roots');
assert.match(readFileSync(helixMasterEditorDocs, 'utf8'), /`atomic-save` \| Whether to use atomic operations to write documents to disk/u, 'T036-ATOMIC-SAVE-HELIX-02 pinned Helix documents atomic-save');
assert.match(readFileSync(helixMasterEditorDocs, 'utf8'), /`indent-heuristic` \| How the indentation for a newly inserted line is computed/u, 'T036-INDENT-HEURISTIC-HELIX-02 pinned Helix documents indent-heuristic fallback');
assert.match(readFileSync(helixMasterEditorDocs, 'utf8'), /\|`start-position` \| Controls behavior for which buffer is initially selected \| `current` \|/u, 'T036-BUFFER-PICKER-HELIX-01 pinned Helix documents buffer-picker start-position');
assert.match(readFileSync(helixMasterEditorDocs, 'utf8'), /\|`hidden` \| Enables ignoring hidden files \| `false`/u, 'T036-FILE-EXPLORER-HIDDEN-HELIX-01 pinned Helix documents file-explorer.hidden');
assert.match(readFileSync(helixMasterEditorDocs, 'utf8'), /\|`follow-symlinks` \| Follow symlinks instead of ignoring them \| `false`/u, 'T036-FILE-EXPLORER-SYMLINKS-HELIX-01 pinned Helix documents file-explorer.follow-symlinks');
assert.match(readFileSync(helixMasterEditorDocs, 'utf8'), /\|`parents` \| Enables reading ignore files from parent directories \| `false`/u, 'T036-FILE-EXPLORER-PARENTS-HELIX-01 pinned Helix documents file-explorer.parents');
assert.match(readFileSync(helixMasterEditorDocs, 'utf8'), /\|`ignore` \| Enables reading `\.ignore` files \| `false`/u, 'T036-FILE-EXPLORER-IGNORE-HELIX-01 pinned Helix documents file-explorer.ignore');
assert.match(readFileSync(helixMasterEditorDocs, 'utf8'), /\|`git-ignore` \| Enables reading `\.gitignore` files \| `false`/u, 'T036-FILE-EXPLORER-GIT-IGNORE-HELIX-01 pinned Helix documents file-explorer.git-ignore');
assert.match(readFileSync(helixMasterEditorDocs, 'utf8'), /\|`git-global` \| Enables reading global `\.gitignore`/u, 'T036-FILE-EXPLORER-GIT-GLOBAL-HELIX-01 pinned Helix documents file-explorer.git-global');
assert.match(readFileSync(helixMasterEditorDocs, 'utf8'), /\|`git-exclude` \| Enables reading `\.git\/info\/exclude` files \| `false`/u, 'T036-FILE-EXPLORER-GIT-EXCLUDE-HELIX-01 pinned Helix documents file-explorer.git-exclude');
assert.match(readFileSync(helixMasterEditorDocs, 'utf8'), /\|`flatten-dirs` \| Enables flattening single child directories \| `true`/u, 'T036-FILE-EXPLORER-FLATTEN-DIRS-HELIX-02 pinned Helix documents file-explorer.flatten-dirs');
  assert.match(readFileSync(helixMasterEditorDocs, 'utf8'), /\| `end-of-line-diagnostics` \|[\s\S]*\| `"hint"` \|/u, 'T036-END-OF-LINE-DIAGNOSTICS-MASTER-DEFAULT-HELIX-01 pinned Helix master documents the hint default');
  assert.match(readFileSync(helixMasterEditorDocs, 'utf8'), /\| `mouse-yank-register` \| Which register to use for mouse yanks\. \|[\s\u00a0]*`\*`/u, 'T036-MOUSE-YANK-REGISTER-HELIX-01 pinned Helix master documents mouse-yank-register and its default');
  assert.match(readFileSync(helixMasterEditorDocs, 'utf8'), /\| `shell` \| Shell to use when running external commands/u, 'T036-SHELL-HELIX-01 pinned Helix master documents editor.shell');
  assert.match(readFileSync(helixMasterEditorDocs, 'utf8'), /\| `clipboard-provider` \| Which API to use for clipboard interaction\./u, 'T036-CLIPBOARD-BUILTIN-HELIX-01 pinned Helix master documents clipboard-provider');
  assert.match(readFileSync(helixMasterEditorDocs, 'utf8'), /One of `pasteboard` .* `none`, or a custom command set\./u, 'T036-CLIPBOARD-BUILTIN-HELIX-02 pinned Helix documents the complete built-in provider set');
  assert.match(readFileSync(helixMasterEditorDocs, 'utf8'), /\| `middle-click-paste` \| Middle click paste support \| `true`/u, 'T036-MIDDLE-CLICK-PASTE-HELIX-01 pinned Helix master documents middle-click-paste');
  assert.match(readFileSync(helixMasterEditorDocs, 'utf8'), /\[editor\.clipboard-provider\.custom\][\s\S]*yank = \{ command = "cat"/u, 'T036-CLIPBOARD-YANK-HELIX-01 pinned Helix master documents custom yank commands');
  assert.match(readFileSync(helixMasterEditorDocs, 'utf8'), /\[editor\.clipboard-provider\.custom\][\s\S]*paste = \{ command = "tee"/u, 'T036-CLIPBOARD-PASTE-HELIX-01 pinned Helix master documents custom paste commands');
  assert.match(readFileSync(helixMasterEditorDocs, 'utf8'), /primary-yank = \{ command = "cat"/u, 'T036-CLIPBOARD-PRIMARY-YANK-HELIX-01 pinned Helix master documents primary yank commands');
  assert.match(readFileSync(helixMasterEditorDocs, 'utf8'), /primary-paste = \{ command = "tee"/u, 'T036-CLIPBOARD-PRIMARY-PASTE-HELIX-01 pinned Helix master documents primary paste commands');
  assert.match(readFileSync(helixMasterEditorDocs, 'utf8'), /\| `kitty-keyboard-protocol` \| Whether to enable Kitty Keyboard Protocol\. Can be `enabled`, `disabled` or `auto` \| `"auto"` \|/u, 'T036-KITTY-KEYBOARD-HELIX-01 pinned Helix master documents kitty-keyboard-protocol values and default');
assert.match(readFileSync(helixMasterEditorDocs, 'utf8'), /\| `cursor-line` \|[\s\S]*\| `"warning"` \|/u, 'T036-INLINE-DIAGNOSTICS-FILTER-MASTER-DEFAULT-HELIX-01 pinned Helix master documents the warning cursor-line default');
assert.match(readFileSync(helixMasterEditorDocs, 'utf8'), /\[editor\.word-completion\][\s\S]*\| `enable` \|[\s\S]*\| `true` \|/u, 'T036-WORD-COMPLETION-ENABLE-HELIX-01 pinned Helix master documents word-completion.enable and its true default');
assert.match(readFileSync(helixMasterEditorDocs, 'utf8'), /\[editor\.word-completion\][\s\S]*\| `trigger-length`\s+\|[^\n]*\| `7`/u, 'T036-WORD-COMPLETION-TRIGGER-LEN-HELIX-01 pinned Helix master documents word-completion.trigger-length and its 7 default');
assert.match(readFileSync(helixMasterEditorDocs, 'utf8'), /\| `level`\s+\| The default level of trust for every workspace\.[^\n]*\| `"servers"` \|/u, 'T036-WORKSPACE-TRUST-LEVEL-HELIX-01 pinned Helix master documents workspace-trust.level and its servers default');
assert.match(readFileSync(helixMasterEditorDocs, 'utf8'), /\| `prompt`\s+\| Whether to show a modal when opening a file in an untrusted workspace\.[^\n]*\| `true`\s+\|/u, 'T036-WORKSPACE-TRUST-PROMPT-HELIX-01 pinned Helix master documents workspace-trust.prompt and its true default');
assert.match(readFileSync(helixMasterEditorDocs, 'utf8'), /\| `trusted`\s+\| Glob patterns whose matching workspaces are trusted without a grant\.[^\n]*\| `\[\]`\s+\|/u, 'T036-WORKSPACE-TRUST-TRUSTED-HELIX-01 pinned Helix master documents workspace-trust.trusted and its empty default');
assert.match(readFileSync(helixMasterEditorDocs, 'utf8'), /\| `goto-reference-include-declaration`\s+\| Include declaration in the goto references popup\.\s+\| `true`\s+\|/u, 'T036-LSP-GOTO-REFERENCES-HELIX-01 pinned Helix master documents goto-reference-include-declaration and its true default');
assert.match(readFileSync(join(import.meta.dir, '../../.artifacts/reference/helix/master/book/src/themes.md'), 'utf8'), /\[theme\][\s\S]*dark = "catppuccin_frappe"[\s\S]*light = "catppuccin_latte"[\s\S]*fallback = "catppuccin_frappe"/u, 'T036-THEME-VARIANTS-HELIX-01 pinned Helix master documents dark, light and fallback theme selectors');
assert.match(readFileSync(join(import.meta.dir, '../../.artifacts/reference/helix/master/book/src/themes.md'), 'utf8'), /dark = "catppuccin_frappe"/u, 'T036-THEME-DARK-HELIX-01 pinned Helix master documents theme.dark');
assert.match(readFileSync(join(import.meta.dir, '../../.artifacts/reference/helix/master/book/src/themes.md'), 'utf8'), /light = "catppuccin_latte"/u, 'T036-THEME-LIGHT-HELIX-01 pinned Helix master documents theme.light');
assert.match(readFileSync(join(import.meta.dir, '../../.artifacts/reference/helix/master/book/src/themes.md'), 'utf8'), /fallback = "catppuccin_frappe"/u, 'T036-THEME-FALLBACK-HELIX-01 pinned Helix master documents theme.fallback');
  assert.match(readFileSync(helixMasterEditorDocs, 'utf8'), /#### `\[editor\.gutters\.diff\]` Section[\s\S]*?There are currently no options for this section\./u, 'T036-GUTTERS-EMPTY-HELIX-02 pinned Helix documents the diff gutter section as optionless');
  assert.match(readFileSync(helixMasterEditorDocs, 'utf8'), /#### `\[editor\.gutters\.spacer\]` Section/u, 'T036-GUTTERS-EMPTY-HELIX-03 pinned Helix documents the spacer gutter section');
  assert.match(readFileSync(fixture, 'utf8'), /^cursorline = false$/m, 'T036-CURSORLINE-HELIX-01 canonical fixture contains editor.cursorline');
  assert.match(readFileSync(fixture, 'utf8'), /^cursorcolumn = false$/m, 'T036-CURSORCOLUMN-HELIX-01 canonical fixture contains editor.cursorcolumn');
  assert.match(readFileSync(fixture, 'utf8'), /^auto-format = true$/m, 'T036-AUTO-FORMAT-HELIX-01 canonical fixture contains editor.auto-format');
  assert.match(readFileSync(fixture, 'utf8'), /^focus-lost = false$/m, 'T036-AUTO-SAVE-HELIX-01 canonical fixture contains editor.auto-save.focus-lost');
  assert.match(readFileSync(fixture, 'utf8'), /^after-delay\.enable = false$/m, 'T036-AUTO-SAVE-HELIX-02 canonical fixture contains editor.auto-save.after-delay.enable');
  assert.match(readFileSync(fixture, 'utf8'), /^after-delay\.timeout = 3000$/m, 'T036-AUTO-SAVE-HELIX-03 canonical fixture contains editor.auto-save.after-delay.timeout');
  assert.match(readFileSync(fixture, 'utf8'), /^default-yank-register = '\"'$/m, 'T036-DEFAULT-YANK-REGISTER-HELIX-01 canonical fixture contains editor.default-yank-register');
  assert.match(readFileSync(fixture, 'utf8'), /^insert-final-newline = true$/m, 'T036-INSERT-FINAL-NEWLINE-HELIX-01 canonical fixture contains editor.insert-final-newline');
  assert.match(readFileSync(fixture, 'utf8'), /^trim-final-newlines = false$/m, 'T036-TRIM-FINAL-NEWLINES-HELIX-01 canonical fixture contains editor.trim-final-newlines');
  assert.match(readFileSync(fixture, 'utf8'), /^trim-trailing-whitespace = false$/m, 'T036-TRIM-TRAILING-WHITESPACE-HELIX-01 canonical fixture contains editor.trim-trailing-whitespace');
  assert.match(readFileSync(fixture, 'utf8'), /^smart-case = true$/m, 'T036-SEARCH-SMART-CASE-HELIX-01 canonical fixture contains editor.search.smart-case');
  assert.match(readFileSync(fixture, 'utf8'), /^wrap-around = true$/m, 'T036-SEARCH-WRAP-AROUND-HELIX-01 canonical fixture contains editor.search.wrap-around');
  assert.match(readFileSync(fixture, 'utf8'), /^rulers = \[\]$/m, 'T036-RULERS-HELIX-01 canonical fixture contains editor.rulers');
  assert.match(readFileSync(fixture, 'utf8'), /^text-width = 80$/m, 'T036-TEXT-WIDTH-HELIX-01 canonical fixture contains editor.text-width');
  assert.match(readFileSync(fixture, 'utf8'), /^workspace-lsp-roots = \[\]$/m, 'T036-WORKSPACE-LSP-ROOTS-HELIX-01 canonical fixture contains editor.workspace-lsp-roots');
  assert.match(readFileSync(fixture, 'utf8'), /^atomic-save = true$/m, 'T036-ATOMIC-SAVE-HELIX-01 canonical fixture contains editor.atomic-save');
  assert.match(readFileSync(fixture, 'utf8'), /^indent-heuristic = "hybrid"$/m, 'T036-INDENT-HEURISTIC-HELIX-01 canonical fixture contains editor.indent-heuristic');
  assert.match(readFileSync(fixture, 'utf8'), /^wrap-at-text-width = false$/m, 'T036-WRAP-TEXT-WIDTH-HELIX-01 canonical fixture contains editor.soft-wrap.wrap-at-text-width');
  assert.match(readFileSync(fixture, 'utf8'), /^hidden = true$/m, 'T036-FILE-PICKER-HIDDEN-HELIX-01 canonical fixture contains editor.file-picker.hidden');
  assert.match(readFileSync(fixture, 'utf8'), /^follow-symlinks = true$/m, 'T036-FILE-PICKER-SYMLINKS-HELIX-01 canonical fixture contains editor.file-picker.follow-symlinks');
  assert.match(readFileSync(fixture, 'utf8'), /^deduplicate-links = true$/m, 'T036-FILE-PICKER-DEDUPE-HELIX-01 canonical fixture contains editor.file-picker.deduplicate-links');
  assert.match(readFileSync(fixture, 'utf8'), /^parents = true$/m, 'T036-FILE-PICKER-PARENTS-HELIX-01 canonical fixture contains editor.file-picker.parents');
  assert.match(readFileSync(fixture, 'utf8'), /^ignore = true$/m, 'T036-FILE-PICKER-IGNORE-HELIX-01 canonical fixture contains editor.file-picker.ignore');
  assert.match(readFileSync(fixture, 'utf8'), /^git-ignore = true$/m, 'T036-FILE-PICKER-GIT-IGNORE-HELIX-01 canonical fixture contains editor.file-picker.git-ignore');
  assert.match(readFileSync(fixture, 'utf8'), /^git-global = true$/m, 'T036-FILE-PICKER-GIT-GLOBAL-HELIX-01 canonical fixture contains editor.file-picker.git-global');
  assert.match(readFileSync(fixture, 'utf8'), /^git-exclude = true$/m, 'T036-FILE-PICKER-GIT-EXCLUDE-HELIX-01 canonical fixture contains editor.file-picker.git-exclude');
  assert.match(readFileSync(fixture, 'utf8'), /^max-depth = 64$/m, 'T036-FILE-PICKER-MAX-DEPTH-HELIX-01 canonical fixture contains editor.file-picker.max-depth');
  assert.match(readFileSync(fixture, 'utf8'), /^display-signature-help-docs = true$/m, 'T036-LSP-SIGNATURE-DOCS-HELIX-01 canonical fixture contains editor.lsp.display-signature-help-docs');
  assert.match(readFileSync(fixture, 'utf8'), /^auto-document-highlight = false$/m, 'T036-LSP-DOCUMENT-HIGHLIGHT-HELIX-01 canonical fixture contains editor.lsp.auto-document-highlight');
  assert.match(readFileSync(fixture, 'utf8'), /left = \["mode", "spinner", "file-name", "code-action-hint"\]/u, 'T036-CODE-ACTION-HINT-STATUSLINE-HELIX-01 canonical fixture contains statusline code-action-hint');
  assert.match(readFileSync(fixture, 'utf8'), /layout = \["diagnostics", "spacer", "line-numbers", "spacer", "diff", "code-action-hint"\]/u, 'T036-CODE-ACTION-HINT-GUTTER-HELIX-01 canonical fixture contains gutter code-action-hint');
  assert.match(readFileSync(fixture, 'utf8'), /^display-messages = true$/m, 'T036-LSP-DISPLAY-MESSAGES-HELIX-01 canonical fixture contains editor.lsp.display-messages');
  assert.match(readFileSync(fixture, 'utf8'), /^display-progress-messages = false$/m, 'T036-LSP-DISPLAY-PROGRESS-HELIX-01 canonical fixture contains editor.lsp.display-progress-messages');
  assert.match(readFileSync(fixture, 'utf8'), /^snippets = true$/m, 'T036-LSP-SNIPPETS-HELIX-01 canonical fixture contains editor.lsp.snippets');
  assert.match(readFileSync(fixture, 'utf8'), /^auto-completion = true$/m, 'T036-AUTO-COMPLETION-HELIX-01 canonical fixture contains editor.auto-completion');
  assert.match(readFileSync(fixture, 'utf8'), /^path-completion = true$/m, 'T036-PATH-COMPLETION-HELIX-01 canonical fixture contains editor.path-completion');
  assert.match(readFileSync(fixture, 'utf8'), /^completion-timeout = 250$/m, 'T036-COMPLETION-TIMEOUT-HELIX-01 canonical fixture contains editor.completion-timeout');
  assert.match(readFileSync(fixture, 'utf8'), /^completion-trigger-len = 2$/m, 'T036-COMPLETION-TRIGGER-LEN-HELIX-01 canonical fixture contains editor.completion-trigger-len');
  assert.match(readFileSync(fixture, 'utf8'), /^preview-completion-insert = true$/m, 'T036-PREVIEW-COMPLETION-INSERT-HELIX-01 canonical fixture contains editor.preview-completion-insert');
  assert.match(readFileSync(fixture, 'utf8'), /^auto-info = true$/m, 'T036-AUTO-INFO-HELIX-01 canonical fixture contains editor.auto-info');
  assert.match(readFileSync(fixture, 'utf8'), /^C-s = ":write"$/m, 'T036-KEYS-HELIX-01 canonical fixture contains Helix typable key commands');
  assert.match(readFileSync(fixture, 'utf8'), /^ret = \["no_op", "no_op"\]$/m, 'T036-KEYS-FORMS-HELIX-01 canonical fixture contains a Helix command sequence');
  assert.match(readFileSync(fixture, 'utf8'), /^"A-x" = "@x<M-s>"$/m, 'T036-KEYS-FORMS-HELIX-02 canonical fixture contains a Helix key macro');
  assert.match(readFileSync(fixture, 'utf8'), /^\[keys\.select\]$/m, 'T036-KEYS-HELIX-01 canonical fixture contains the select key context');
  assert.match(readFileSync(fixture, 'utf8'), /^completion-replace = false$/m, 'T036-COMPLETION-REPLACE-HELIX-01 canonical fixture contains editor.completion-replace');
  assert.match(readFileSync(fixture, 'utf8'), /^color-modes = false$/m, 'T036-COLOR-MODES-HELIX-01 canonical fixture contains editor.color-modes');
  assert.match(readFileSync(fixture, 'utf8'), /^rainbow-brackets = false$/m, 'T036-RAINBOW-BRACKETS-HELIX-01 canonical fixture contains editor.rainbow-brackets');
  assert.match(readFileSync(fixture, 'utf8'), /^true-color = false$/m, 'T036-TRUE-COLOR-HELIX-01 canonical fixture contains editor.true-color');
  assert.match(readFileSync(fixture, 'utf8'), /^undercurl = false$/m, 'T036-UNDERCURL-HELIX-01 canonical fixture contains editor.undercurl');
  assert.match(readFileSync(fixture, 'utf8'), /^bufferline = "never"$/m, 'T036-BUFFERLINE-HELIX-01 canonical fixture contains editor.bufferline');
  assert.match(readFileSync(fixture, 'utf8'), /^default-line-ending = "native"$/m, 'T036-DEFAULT-LINE-ENDING-HELIX-01 canonical fixture contains editor.default-line-ending');
  assert.match(readFileSync(fixture, 'utf8'), /^popup-border = "none"$/m, 'T036-POPUP-BORDER-HELIX-01 canonical fixture contains editor.popup-border');
  assert.match(readFileSync(fixture, 'utf8'), /^left = \["mode", "spinner", "file-name", "code-action-hint"\]$/m, 'T036-STATUSLINE-LAYOUT-HELIX-01 canonical fixture contains editor.statusline.left');
  assert.match(readFileSync(fixture, 'utf8'), /^center = \[\]$/m, 'T036-STATUSLINE-LAYOUT-HELIX-01 canonical fixture contains editor.statusline.center');
  assert.match(readFileSync(fixture, 'utf8'), /^right = \["diagnostics", "selections", "register", "position", "file-encoding"\]$/m, 'T036-STATUSLINE-LAYOUT-HELIX-01 canonical fixture contains editor.statusline.right');
  assert.match(readFileSync(helixMasterEditorDocs, 'utf8'), /\| `file-type` \|/u, 'T036-STATUSLINE-ELEMENTS-HELIX-01 pinned Helix statusline catalog names file-type');
  assert.match(readFileSync(fixture, 'utf8'), /^auto-signature-help = true$/m, 'T036-AUTO-SIGNATURE-HELP-HELIX-01 canonical fixture contains editor.lsp.auto-signature-help');
  assert.match(readFileSync(fixture, 'utf8'), /^display-inlay-hints = false$/m, 'T036-LSP-INLAY-HINTS-HELIX-01 canonical fixture contains editor.lsp.display-inlay-hints');
  assert.match(readFileSync(fixture, 'utf8'), /^inlay-hints-length-limit = 80$/m, 'T036-LSP-INLAY-HINTS-LIMIT-HELIX-01 canonical fixture contains editor.lsp.inlay-hints-length-limit');
  assert.match(readFileSync(fixture, 'utf8'), /^display-color-swatches = true$/m, 'T036-LSP-COLOR-SWATCHES-HELIX-01 canonical fixture contains editor.lsp.display-color-swatches');
  assert.match(readFileSync(fixture, 'utf8'), /^\[editor\.soft-wrap\]$/m, 'T036-SOFT-WRAP-HELIX-01 canonical fixture contains editor.soft-wrap');
  assert.match(readFileSync(fixture, 'utf8'), /^enable = false$/m, 'T036-SOFT-WRAP-HELIX-01 canonical fixture contains editor.soft-wrap.enable');
  assert.match(readFileSync(fixture, 'utf8'), /^max-wrap = 20$/m, 'T036-SOFT-WRAP-MAX-HELIX-01 canonical fixture contains editor.soft-wrap.max-wrap');
  assert.match(readFileSync(fixture, 'utf8'), /^max-indent-retain = 40$/m, 'T036-SOFT-WRAP-INDENT-HELIX-01 canonical fixture contains editor.soft-wrap.max-indent-retain');
  assert.match(readFileSync(fixture, 'utf8'), /^wrap-indicator = "↪ "$/m, 'T036-WRAP-INDICATOR-HELIX-01 canonical fixture contains editor.soft-wrap.wrap-indicator');
  assert.match(readFileSync(fixture, 'utf8'), /^cursor-line = "disable"$/m, 'T036-INLINE-DIAGNOSTICS-FILTER-HELIX-01 canonical fixture contains editor.inline-diagnostics.cursor-line');
  assert.match(readFileSync(fixture, 'utf8'), /^other-lines = "disable"$/m, 'T036-INLINE-DIAGNOSTICS-FILTER-HELIX-01 canonical fixture contains editor.inline-diagnostics.other-lines');
  assert.match(readFileSync(fixture, 'utf8'), /^end-of-line-diagnostics = "disable"$/m, 'T036-END-OF-LINE-DIAGNOSTICS-HELIX-01 canonical fixture contains editor.end-of-line-diagnostics');
  assert.match(readFileSync(fixture, 'utf8'), /^prefix-len = 1$/m, 'T036-INLINE-DIAGNOSTICS-PREFIX-LEN-HELIX-01 canonical fixture contains editor.inline-diagnostics.prefix-len');
  assert.match(readFileSync(fixture, 'utf8'), /^max-wrap = 20$/m, 'T036-INLINE-DIAGNOSTICS-MAX-WRAP-HELIX-01 canonical fixture contains editor.inline-diagnostics.max-wrap');
  assert.match(readFileSync(fixture, 'utf8'), /^min-diagnostic-width = 40$/m, 'T036-INLINE-DIAGNOSTICS-MIN-WIDTH-HELIX-01 canonical fixture contains editor.inline-diagnostics.min-diagnostic-width');
  assert.match(readFileSync(fixture, 'utf8'), /^max-diagnostics = 10$/m, 'T036-INLINE-DIAGNOSTICS-MAX-HELIX-01 canonical fixture contains editor.inline-diagnostics.max-diagnostics');
  assert.match(readFileSync(fixture, 'utf8'), /^normal = "block"$/m, 'T036-CURSOR-SHAPE-HELIX-01 canonical fixture contains editor.cursor-shape.normal');
  assert.match(readFileSync(fixture, 'utf8'), /^insert = "block"$/m, 'T036-CURSOR-SHAPE-HELIX-01 canonical fixture contains editor.cursor-shape.insert');
  assert.match(readFileSync(fixture, 'utf8'), /^select = "block"$/m, 'T036-CURSOR-SHAPE-HELIX-01 canonical fixture contains editor.cursor-shape.select');
  const output = execFileSync(helix, ['-c', fixture, '--health'], { cwd: temporary, env: { ...process.env, HOME: temporary }, encoding: 'utf8', maxBuffer: 4 * 1024 * 1024 });
  assert.match(output, /Config file:/, 'T036-LSP-ENABLE-HELIX-01 Helix accepts the canonical fixture containing editor.lsp.enable');
  assert.match(output, /Config file:/, 'T036-CONTINUE-COMMENTS-HELIX-01 Helix accepts the canonical fixture containing editor.continue-comments');
  assert.match(output, /Config file:/, 'T036-LOADING-CLI-HELIX-01 pinned Helix accepts an explicit -c config path');
  const workspaceOutput = execFileSync(helix, ['--health'], { cwd: temporary, env: { ...process.env, HOME: temporary }, encoding: 'utf8', maxBuffer: 4 * 1024 * 1024 });
  assert.match(workspaceOutput, /Config file:/, 'T036-LOADING-WORKSPACE-HELIX-01 Helix accepts a workspace .helix/config.toml');
  const invalidFixture = join(temporary, 'helix-invalid.toml');
  writeFileSync(invalidFixture, '[editor]\nnot-a-setting = true\n');
  const invalidOutput = execFileSync(helix, ['-c', invalidFixture, '--health'], { cwd: temporary, env: { ...process.env, HOME: temporary }, encoding: 'utf8', maxBuffer: 4 * 1024 * 1024 });
  assert.match(invalidOutput, /unknown field `not-a-setting`/u, 'T036-UNKNOWN-FIELDS-HELIX-01 pinned Helix reports unknown config fields');
  console.log('T036-LSP-ENABLE-HELIX-01 passed: pinned Helix 25.07.1 accepted editor.lsp.enable in the canonical fixture.');
} finally {
  rmSync(temporary, { recursive: true, force: true });
}
