import type { Disposable, Result } from '../../contracts/src/index';
import { FocusGraph, type FocusGraphFailure, type FocusTarget } from '../../workbench/src/index';
export type PickerMode = 'file' | 'buffer' | 'command' | 'theme' | 'config' | 'git' | 'diagnostic';
export type PickerEntryKind = PickerMode;
export interface PickerEntry { readonly id: string; readonly mode: PickerMode; readonly kind: PickerEntryKind; readonly label: string; readonly detail: string; readonly value: string; readonly rootId: string | undefined; readonly relativePath: string | undefined; readonly hidden: boolean; readonly score: number; readonly severity?: 1 | 2 | 3 | 4; }
export interface PickerReadModel { readonly contractVersion: 1; readonly mode: PickerMode; readonly query: string; readonly generation: number; readonly state: 'loading' | 'ready' | 'empty' | 'stale' | 'error'; readonly entries: readonly PickerEntry[]; readonly selectedId: string | undefined; readonly totalMatches: number; readonly truncated: boolean; readonly message: string | undefined; }
export type PickerFailure = { readonly kind: 'cancelled' } | { readonly kind: 'stale'; readonly generation: number } | { readonly kind: 'not-ready'; readonly mode: PickerMode; readonly message: string } | { readonly kind: 'provider'; readonly message: string };
export interface PickerQuerySource { readonly model: PickerReadModel; query(mode: PickerMode, query: string, options?: { readonly limit?: number; readonly includeHidden?: boolean }): Promise<Result<PickerReadModel, PickerFailure>>; cancel(): void; select(id: string): boolean; }
export interface PickerReadPort { readonly model: PickerReadModel; subscribe(listener: (model: PickerReadModel) => void): Disposable; }
export class PickerModelBridge implements PickerReadPort, Disposable {
  #model: PickerReadModel; readonly #source: PickerQuerySource; readonly #listeners = new Set<(model: PickerReadModel) => void>(); #disposed = false;
  constructor(source: PickerQuerySource) { this.#source = source; this.#model = source.model; }
  get model(): PickerReadModel { return this.#model; }
  subscribe(listener: (model: PickerReadModel) => void): Disposable { if (this.#disposed) throw new Error('picker-model-bridge-disposed'); this.#listeners.add(listener); return { dispose: () => { this.#listeners.delete(listener); } }; }
  async query(mode: PickerMode, query: string, options: { readonly limit?: number; readonly includeHidden?: boolean } = {}): Promise<Result<PickerReadModel, PickerFailure>> { if (this.#disposed) return { ok: false, error: { kind: 'provider', message: 'picker model bridge is disposed' } }; const result = await this.#source.query(mode, query, options); if (result.ok) { this.#model = result.value; this.notify(); } return result; }
  cancel(): void { if (!this.#disposed) { this.#source.cancel(); this.#model = this.#source.model; this.notify(); } }
  select(id: string): boolean { if (this.#disposed) return false; const selected = this.#source.select(id); if (selected) { this.#model = this.#source.model; this.notify(); } return selected; }
  dispose(): void { if (!this.#disposed) { this.#disposed = true; this.#source.cancel(); this.#listeners.clear(); } }
  private notify(): void { for (const listener of [...this.#listeners]) listener(this.#model); }
}
export interface PickerFocusLifecycleOptions { readonly focus: FocusGraph; readonly targetId?: string; readonly onPreview?: (entry: PickerEntry) => void | Promise<void>; readonly onCancelPreview?: () => void | Promise<void>; }
export type PickerFocusFailure = { readonly kind: 'already-open' } | { readonly kind: 'not-open' } | { readonly kind: 'focus'; readonly cause: FocusGraphFailure };
export class PickerFocusLifecycle implements Disposable {
  readonly #focus: FocusGraph; readonly #target: FocusTarget; readonly #onPreview: PickerFocusLifecycleOptions['onPreview']; readonly #onCancelPreview: PickerFocusLifecycleOptions['onCancelPreview']; #registration: Disposable | undefined; #previewEntry: PickerEntry | undefined; #disposed = false;
  constructor(options: PickerFocusLifecycleOptions) { this.#focus = options.focus; this.#onPreview = options.onPreview; this.#onCancelPreview = options.onCancelPreview; this.#target = Object.freeze({ id: options.targetId ?? 'xi.picker', kind: 'picker', contexts: Object.freeze(['picker', 'query-input']) }); }
  get isOpen(): boolean { return this.#registration !== undefined; } get previewEntry(): PickerEntry | undefined { return this.#previewEntry; } get targetId(): string { return this.#target.id; }
  open(): Result<void, PickerFocusFailure> { if (this.#disposed) return { ok: false, error: { kind: 'focus', cause: { kind: 'graph-disposed' } } }; if (this.#registration !== undefined) return { ok: false, error: { kind: 'already-open' } }; const opened = this.#focus.openOverlay(this.#target); if (!opened.ok) return { ok: false, error: { kind: 'focus', cause: opened.error } }; this.#registration = opened.value; return { ok: true, value: undefined }; }
  async preview(entry: PickerEntry): Promise<Result<void, PickerFocusFailure>> { if (this.#registration === undefined) return { ok: false, error: { kind: 'not-open' } }; try { await this.#onPreview?.(entry); this.#previewEntry = entry; return { ok: true, value: undefined }; } catch { return { ok: false, error: { kind: 'focus', cause: { kind: 'invalid-target', message: 'preview failed' } } }; } }
  async cancel(): Promise<Result<void, PickerFocusFailure>> { if (this.#registration === undefined) return { ok: false, error: { kind: 'not-open' } }; try { await this.#onCancelPreview?.(); this.#previewEntry = undefined; this.#registration.dispose(); this.#registration = undefined; return { ok: true, value: undefined }; } catch { return { ok: false, error: { kind: 'focus', cause: { kind: 'invalid-target', message: 'preview cancellation failed' } } }; } }
  close(): Result<void, PickerFocusFailure> { if (this.#registration === undefined) return { ok: false, error: { kind: 'not-open' } }; this.#registration.dispose(); this.#registration = undefined; this.#previewEntry = undefined; return { ok: true, value: undefined }; }
  dispose(): void { if (!this.#disposed) { this.#disposed = true; this.#registration?.dispose(); this.#registration = undefined; this.#previewEntry = undefined; } }
}
export interface PickerTheme { readonly background: string; readonly surface: string; readonly surfaceActive: string; readonly foreground: string; readonly muted: string; readonly accent: string; readonly error: string; readonly border?: string; }
export const DEFAULT_PICKER_THEME: PickerTheme = Object.freeze({ background: '#FAF9F6', surface: '#F1F0EC', surfaceActive: '#E7EDF4', foreground: '#24292E', muted: '#60666D', accent: '#245A88', error: '#A52A36', border: '#D5D4CF' });
const modeLabel = (mode: PickerMode): string => ({ file: 'Files', buffer: 'Buffers', command: 'Commands', theme: 'Themes', config: 'Config', git: 'Git', diagnostic: 'Diagnostics' })[mode];
export function formatPickerLines(model: PickerReadModel, width: number, maxRows: number, scrollOffset = 0): readonly string[] { const safeWidth = Math.max(1, Math.trunc(width)); const safeRows = Math.max(1, Math.trunc(maxRows)); if (safeRows === 1) return Object.freeze([`>${model.query}`.slice(0, safeWidth)]); const lines = [`${modeLabel(model.mode)}  >${model.query}`.slice(0, safeWidth)]; const multiRoot = new Set(model.entries.map(entry => entry.rootId)).size > 1; for (const entry of model.entries.slice(Math.max(0, Math.trunc(scrollOffset)), Math.max(0, Math.trunc(scrollOffset)) + Math.max(0, safeRows - 2))) lines.push(`${entry.id === model.selectedId ? '▸ ' : '  '}${entry.label}${entry.detail.length === 0 || (entry.mode === 'file' && !multiRoot) ? '' : `  ${entry.detail}`}`.slice(0, safeWidth)); lines.push((model.message ?? `${model.totalMatches}${model.truncated ? '+' : ''} matches · ↑↓ C-n/C-p move · Enter open · Esc cancel`).slice(0, safeWidth)); return Object.freeze(lines); }
export function pickerRowIds(model: PickerReadModel, offset: number, rows: number): readonly (string | undefined)[] { return [undefined, ...model.entries.slice(Math.max(0, offset), Math.max(0, offset) + Math.max(0, rows - 2)).map(entry => entry.id), undefined].slice(0, Math.max(0, rows)); }
