import type { Disposable, Result } from '../../contracts/src/index';
import type { FocusGraph, FocusGraphFailure } from '../../workbench/src/index';
export type DirectoryDraftEntryKind = 'file' | 'directory' | 'symlink' | 'other';
export type DirectoryDraftRowOrigin = 'base' | 'copy' | 'unbound';
export interface DirectoryDraftMetadata { readonly kind: DirectoryDraftEntryKind; readonly stableIdentity: string | undefined; readonly sizeBytes: number | undefined; readonly modifiedMilliseconds: number | undefined; readonly sourcePath: string; }
export interface DirectoryDraftRow { readonly id: string; readonly sourceId: string | undefined; readonly anchor: { readonly id: string; readonly offsetUtf16: number }; readonly line: number; readonly escapedName: string; readonly rawName: string | undefined; readonly origin: DirectoryDraftRowOrigin; readonly metadata: DirectoryDraftMetadata | undefined; }
export interface DirectoryOperationPlan { readonly contractVersion: 1; readonly directoryPath: string; readonly baseGeneration: number; readonly operations: readonly DirectoryOperation[]; }
export type DirectoryOperation = { readonly kind: 'rename'; readonly rowId: string; readonly sourceId: string; readonly from: string; readonly to: string; readonly sourcePath: string; readonly destinationPath: string } | { readonly kind: 'trash'; readonly rowId: string; readonly sourceId: string; readonly sourcePath: string } | { readonly kind: 'copy'; readonly rowId: string; readonly sourceId: string; readonly sourcePath: string; readonly destinationPath: string };
export interface DirectoryDraftError { readonly rowId: string | undefined; readonly line: number | undefined; readonly column: number | undefined; readonly kind: string; readonly message: string; }
export interface DirectoryDraftReadModel { readonly contractVersion: 1; readonly generation: number; readonly directoryPath: string; readonly text: string; readonly rows: readonly DirectoryDraftRow[]; readonly dirty: boolean; readonly focus: 'edit' | 'review'; readonly review: DirectoryOperationPlan | undefined; readonly error: DirectoryDraftError | undefined; }
export interface DirectoryDraftReadPort { readonly model: DirectoryDraftReadModel; subscribe(listener: (model: DirectoryDraftReadModel) => void): Disposable; }
export interface DirectoryReviewTheme { readonly background: string; readonly surface: string; readonly surfaceActive: string; readonly foreground: string; readonly muted: string; readonly border: string; readonly accent: string; readonly error: string; readonly rename: string; readonly copy: string; readonly trash: string; }
export const DEFAULT_DIRECTORY_REVIEW_THEME: DirectoryReviewTheme = Object.freeze({ background: '#FAF9F6', surface: '#F1F0EC', surfaceActive: '#E7EDF4', foreground: '#24292E', muted: '#60666D', border: '#D5D4CF', accent: '#245A88', error: '#A52A36', rename: '#8A5A00', copy: '#367C4A', trash: '#A52A36' });
const operationText = (operation: DirectoryOperation): string => operation.kind === 'rename' ? `↪ ${operation.from} → ${operation.to}` : operation.kind === 'copy' ? `+ ${operation.sourcePath} → ${operation.destinationPath}` : `× ${operation.sourcePath}`;
export function formatDirectoryReviewLines(model: DirectoryDraftReadModel, width: number, maxRows: number): readonly string[] { const safeWidth = Math.max(1, Math.trunc(width)); const rows = [`${model.focus === 'review' ? 'Review' : 'Directory'}  ${model.directoryPath}`]; if (model.error !== undefined) rows.push(`${model.error.line === undefined ? '' : `line ${model.error.line + 1}: `}${model.error.message}`); else if (model.focus === 'review' && model.review !== undefined) rows.push(...model.review.operations.map(operationText)); else rows.push(...model.rows.map(row => `${row.origin === 'copy' ? '+ ' : row.origin === 'unbound' ? '? ' : '  '}${row.escapedName}`)); rows.push(model.error === undefined ? model.focus === 'review' ? 'Enter apply  ·  Esc cancel' : ':w review  ·  u undo' : 'Draft preserved  ·  fix row and retry'); return Object.freeze(rows.slice(0, Math.max(1, maxRows)).map(row => row.slice(0, safeWidth))); }
export interface DirectoryReviewFocusLifecycleOptions { readonly focus: FocusGraph; readonly targetId?: string; readonly onCancelReview?: () => void | Promise<void>; }
export type DirectoryReviewFocusFailure = { readonly kind: 'already-open' } | { readonly kind: 'not-open' } | { readonly kind: 'focus'; readonly cause: FocusGraphFailure };
export class DirectoryReviewFocusLifecycle implements Disposable { readonly #focus: FocusGraph; readonly #targetId: string; readonly #onCancelReview: DirectoryReviewFocusLifecycleOptions['onCancelReview']; #registration: Disposable | undefined; #disposed = false; constructor(options: DirectoryReviewFocusLifecycleOptions) { this.#focus = options.focus; this.#targetId = options.targetId ?? 'xi.directory-review'; this.#onCancelReview = options.onCancelReview; } get isOpen(): boolean { return this.#registration !== undefined; } get targetId(): string { return this.#targetId; } open(): Result<void, DirectoryReviewFocusFailure> { if (this.#disposed) return { ok: false, error: { kind: 'focus', cause: { kind: 'graph-disposed' } } }; if (this.#registration !== undefined) return { ok: false, error: { kind: 'already-open' } }; const opened = this.#focus.openOverlay({ id: this.#targetId, kind: 'overlay', contexts: ['modal-review'] }); if (!opened.ok) return { ok: false, error: { kind: 'focus', cause: opened.error } }; this.#registration = opened.value; return { ok: true, value: undefined }; } async cancel(): Promise<Result<void, DirectoryReviewFocusFailure>> { if (this.#registration === undefined) return { ok: false, error: { kind: 'not-open' } }; try { await this.#onCancelReview?.(); this.#registration.dispose(); this.#registration = undefined; return { ok: true, value: undefined }; } catch { return { ok: false, error: { kind: 'focus', cause: { kind: 'invalid-target', message: 'review cancellation failed' } } }; } } close(): Result<void, DirectoryReviewFocusFailure> { if (this.#registration === undefined) return { ok: false, error: { kind: 'not-open' } }; this.#registration.dispose(); this.#registration = undefined; return { ok: true, value: undefined }; } dispose(): void { if (!this.#disposed) { this.#disposed = true; this.#registration?.dispose(); this.#registration = undefined; } } }
