import type { Disposable, CommandAvailabilityContext } from '../../contracts/src/index';
import type { PrefixHelpHint, PrefixHelpReadModel, PrefixHelpRequest } from '../../workbench/src/index';
export interface PrefixHelpClock { setTimeout(callback: () => void, milliseconds: number): unknown; clearTimeout(handle: unknown): void; }
export interface PrefixHelpGenerations { readonly registryGeneration: number; readonly configGeneration: number; readonly focusGeneration: number; }
export interface PrefixHelpSource { readGenerations(): PrefixHelpGenerations; readPrefixHelp(request: PrefixHelpRequest): PrefixHelpReadModel; }
export interface PrefixHelpReadPort { readonly model: PrefixHelpReadModel | undefined; subscribe(listener: (model: PrefixHelpReadModel | undefined) => void): Disposable; }
export interface PrefixHelpControllerOptions { readonly delayMilliseconds?: number; readonly clock?: PrefixHelpClock; }
const systemClock: PrefixHelpClock = Object.freeze({ setTimeout: (callback: () => void, milliseconds: number) => setTimeout(callback, milliseconds), clearTimeout: (handle: unknown) => clearTimeout(handle as ReturnType<typeof setTimeout>) });
export class PrefixHelpController implements PrefixHelpReadPort, Disposable {
  readonly #source: PrefixHelpSource; readonly #delayMilliseconds: number; readonly #clock: PrefixHelpClock; readonly #listeners = new Set<(model: PrefixHelpReadModel | undefined) => void>(); #timer: unknown; #serial = 0; #disposed = false; #model: PrefixHelpReadModel | undefined;
  constructor(source: PrefixHelpSource, options: PrefixHelpControllerOptions = {}) { this.#source = source; this.#delayMilliseconds = options.delayMilliseconds ?? 250; if (!Number.isSafeInteger(this.#delayMilliseconds) || this.#delayMilliseconds < 0) throw new TypeError('prefix-help-delay-must-be-nonnegative'); this.#clock = options.clock ?? systemClock; }
  get model(): PrefixHelpReadModel | undefined { return this.#model; }
  subscribe(listener: (model: PrefixHelpReadModel | undefined) => void): Disposable { if (this.#disposed) throw new Error('prefix-help-controller-disposed'); this.#listeners.add(listener); return { dispose: () => { this.#listeners.delete(listener); } }; }
  schedule(request: PrefixHelpRequest): void { if (this.#disposed) return; this.clearTimer(); this.clearModel(); if (request.pendingKeys.length === 0 && request.parserContinuations.length === 0) return; const serial = ++this.#serial; const captured = this.#source.readGenerations(); this.#timer = this.#clock.setTimeout(() => { this.#timer = undefined; if (this.#disposed || serial !== this.#serial) return; const current = this.#source.readGenerations(); if (!sameGenerations(captured, current) || current.configGeneration !== request.configGeneration) return; const model = this.#source.readPrefixHelp(Object.freeze({ ...request, ...(request.availability === undefined ? {} : { availability: Object.freeze({ contexts: Object.freeze([...request.availability.contexts]), capabilities: Object.freeze([...request.availability.capabilities]) } as CommandAvailabilityContext) }) })); if (!sameGenerations(captured, { registryGeneration: model.registryGeneration, focusGeneration: model.focusGeneration, configGeneration: model.configGeneration }) || model.hints.length === 0) return; this.#model = model; this.notify(); }, this.#delayMilliseconds); }
  cancel(): void { if (!this.#disposed) { this.#serial += 1; this.clearTimer(); this.clearModel(); } }
  completeCommand(): void { this.cancel(); }
  dispose(): void { if (!this.#disposed) { this.#disposed = true; this.#serial += 1; this.clearTimer(); this.#model = undefined; this.#listeners.clear(); } }
  private clearTimer(): void { if (this.#timer !== undefined) { this.#clock.clearTimeout(this.#timer); this.#timer = undefined; } }
  private clearModel(): void { if (this.#model !== undefined) { this.#model = undefined; this.notify(); } }
  private notify(): void { for (const listener of [...this.#listeners]) listener(this.#model); }
}
export interface PrefixHelpPanelTheme { readonly background: string; readonly foreground: string; readonly muted: string; readonly accent: string; readonly unavailable: string; }
export const DEFAULT_PREFIX_HELP_THEME: PrefixHelpPanelTheme = Object.freeze({ background: '#F1F0EC', foreground: '#24292E', muted: '#60666D', accent: '#245A88', unavailable: '#A52A36' });
const clip = (value: string, width: number): string => value.length <= width ? value : width <= 1 ? '…' : `${value.slice(0, width - 1)}…`;
export function formatPrefixHelpLines(model: PrefixHelpReadModel | undefined, width: number, maxRows: number): readonly string[] { if (model === undefined || maxRows <= 0 || width <= 0) return Object.freeze([]); const safeWidth = Math.max(1, Math.trunc(width)); const rows = Math.max(1, Math.trunc(maxRows)); const prefix = model.pendingKeys.length === 0 ? 'Prefix' : `Prefix ${model.pendingKeys.join(' ')}`; const compact = model.compactHint ?? `${prefix}: no legal continuation`; if (safeWidth < 48 || rows === 1) return Object.freeze([clip(compact, safeWidth)]); const output = [clip(`${prefix}  (${model.hints.length} hints)`, safeWidth)]; for (const hint of model.hints) { if (output.length >= rows) break; const state = hint.available ? '' : ` [${hint.disabledReason ?? 'unavailable'}]`; const alias = hint.aliases.length === 0 ? '' : ` (${hint.aliases.join(', ')})`; output.push(clip(`  ${hint.keyLabel}  ${hint.title}${alias} — ${hint.description}${state}`, safeWidth)); } return Object.freeze(output); }
function sameGenerations(left: PrefixHelpGenerations, right: PrefixHelpGenerations): boolean { return left.registryGeneration === right.registryGeneration && left.configGeneration === right.configGeneration && left.focusGeneration === right.focusGeneration; }
export type { PrefixHelpHint };
