export type {
  CellHitTarget,
  CellPoint,
  CellWidthPolicy,
  DiffFillerHitTarget,
  DiffFillerRow,
  FoldHitTarget,
  FoldRegion,
  FrameIdentity,
  GutterHitTarget,
  LayoutCacheStats,
  LayoutFailure,
  LayoutFrameId,
  LayoutGeneration,
  LayoutHit,
  LayoutOptions,
  ProjectedEndpoint,
  ProjectedSelection,
  ScreenCell,
  ScreenRow,
  ScrollbarHitTarget,
  SplitSeparatorHitTarget,
  TextHitTarget,
  UiControlHitTarget,
  ViewportAnchor,
  ViewportProjectionInput,
  VirtualAnnotation,
  VirtualAnnotationHitTarget,
  VisibleFrame,
} from './types';
export { defaultCellWidthPolicy } from './graphemes';
export { ViewportLayout, resolveScrollAnchor } from './viewport';
export { projectComparisonSide, type ComparisonRow } from './comparison';
