export type { ServiceFactory, ServiceFactoryContext, ServicePort } from '../../contracts/src/index.ts';
export { LanguageTransport, startLanguageTransport } from '../language/index';
export {
  LanguageServerPool,
  LanguageServerSession,
  createLanguageServerIdentity,
  resolveLanguageRoot,
} from '../language/index';
export type {
  LanguageStartFailure,
  LanguageConfigurationItem,
  LanguageDocumentSnapshot,
  LanguageDynamicCapability,
  LanguageProgressEvent,
  LanguageRetryPolicy,
  LanguageServerHealth,
  LanguageServerIdentity,
  LanguageServerIdentityInput,
  LanguageServerSessionOptions,
  LanguageServerSessionState,
  LanguageServerStateChange,
  LanguageSessionFailure,
  LanguageTransportDiagnostics,
  LanguageTransportOptions,
  LanguageTransportState,
  LanguageWorkspaceFolder,
  ResolvedLanguageRoot,
  RootMarkerProbe,
  RootResolutionFailure,
  RootResolutionRequest,
  StderrRecord,
} from '../language/index';
export {
  LanguageDocumentSync,
  negotiatePositionEncoding,
  offsetToPosition,
  positionToOffset,
  DiagnosticStore,
  SemanticTokenStore,
  CompletionController,
  LanguageServerCompletionProvider,
  SignatureController,
  LanguageServerSignatureProvider,
  LanguageNavigationController,
  LanguageServerNavigationProvider,
  PullDiagnosticStore,
  HierarchyController,
  LanguageServerHierarchyProvider,
  LanguagePresentationFeatures,
  WorkspaceEditCoordinator,
  LanguageServerWorkspaceEditProvider,
  expandSnippet,
  SnippetSession,
} from '../language/index';
export type {
  InitializeParams,
  InitializeResult,
  DiagnosticPublish,
  DiagnosticReadModel,
  LanguageDiagnostic,
  LanguageDiagnosticRange,
  SemanticTokenLegend,
  SemanticTokenSpan,
  SemanticTokenRequest,
  SemanticTokenFullResult,
  SemanticTokenDeltaEdit,
  SemanticTokenDeltaResult,
  SemanticTokenRangeResult,
  SemanticTokenResult,
  SemanticTokenFailure,
  SemanticTokenSnapshot,
  CompletionPosition,
  CompletionTextEdit,
  CompletionItem,
  CompletionRequest,
  CompletionList,
  CompletionFailure,
  CompletionAction,
  CompletionReadModel,
  CompletionProvider,
  SignaturePosition,
  SignatureRequest,
  SignatureParameter,
  SignatureInformation,
  SignatureFailure,
  SignatureList,
  SignatureReadModel,
  SignatureProvider,
  LanguageLocation,
  LanguageSymbol,
  NavigationRequest,
  NavigationFailure,
  NavigationProvider,
  NavigationReadModel,
  PullDiagnosticReport,
  PullDiagnosticProvider,
  PullDiagnosticFailure,
  PullDiagnosticSnapshot,
  HierarchyItem,
  DocumentLink,
  HierarchyKind,
  HierarchyRelation,
  HierarchyProvider,
  HierarchyFailure,
  HierarchyReadState,
  HierarchyReadModel,
  SelectionRange,
  FoldRange,
  InlayHint,
  CodeLens,
  FoldingResult,
  SelectionRangeResult,
  HintResult,
  FoldingFailure,
  PresentationResolve,
  PresentationExecute,
  WorkspaceTextEdit,
  WorkspaceResourceOperation,
  WorkspaceEditProposal,
  WorkspaceEditTarget,
  WorkspaceEditPort,
  WorkspaceEditFailure,
  WorkspaceEditPosition,
  WorkspaceEditRequest,
  CodeActionRequest,
  LanguageCodeAction,
  WorkspaceEditProviderFailure,
  SnippetEdit,
  SnippetTabstop,
  SnippetExpansion,
  SnippetFailure,
  LanguageSyncDocument,
  LanguageSyncFailure,
  LanguageSyncOptions,
  LanguageSyncServerCapabilities,
  LanguageSyncSnapshot,
  LspPosition,
  LspRange,
} from '../language/index';
export {
  IncrementalSyntaxHighlighter,
  highlightOnce,
  initializeTreeSitterRuntime,
  loadTreeSitterGrammar,
  TREE_SITTER_RUNTIME_VERSION,
} from '../syntax/index';
export { WorkspaceReplaceService, applyReplacementEdits } from '../search/replace';
export type { ReplaceTarget, ReplacementEdit, ReplacePlan, ReplaceApplyPort, ReplaceFailure, ReplaceJournal, ReplaceJournalEntry, ReplaceApplyResult } from '../search/replace';
export { TaskController } from '../tasks/index';
export type { TaskSpec, TaskProcess, TaskProcessFactory, TaskOutputSnapshot, TaskFailure } from '../tasks/index';
export { FormatterPipeline, createExternalFormatter, createLspFormatter } from '../formatting/index';
export type {
  ExternalFormatterOptions,
  FormatDocument,
  FormatRange,
  FormatterEdit,
  FormatterSpec,
  FormatterFailure,
  FormatResult,
  LspFormatterProvider,
} from '../formatting/index';
export { parsePorcelainV2Z, GitStatusCache } from '../git/index';
export type { GitEntryState, GitStatusEntry, GitStatusSnapshot, GitFailure } from '../git/index';
export { GitMutationCoordinator } from '../git/index';
export type { GitMutationExecutor, GitMutationContext, GitMutationFailure } from '../git/index';
export { GitHistoryController } from '../git/index';
export type { GitHistoryEntry, GitConflictState } from '../git/index';

export {
  EXPLORER_CONTRACT_VERSION,
  ExplorerNavigationController,
  ExplorerTree,
} from '../files/index';
export {
  DIRECTORY_DRAFT_CONTRACT_VERSION,
  DirectoryDraft,
  createDirectoryDraft,
  decodeDirectoryName,
  escapeDirectoryName,
} from '../files/index';
export type {
  DirectoryDraftAnchor,
  DirectoryDraftEntryKind,
  DirectoryDraftError,
  DirectoryDraftMetadata,
  DirectoryDraftOptions,
  DirectoryDraftReadModel,
  DirectoryDraftReadPort,
  DirectoryDraftRow,
  DirectoryDraftRowOrigin,
  DirectoryDraftSourceEntry,
  DirectoryDraftValidationFailure,
  DirectoryOperation,
  DirectoryOperationPlan,
  DirectoryYankBuffer,
} from '../files/index';
export {
  FILE_OPERATION_CONTRACT_VERSION,
  JournaledFilesystemOperations,
  decodeFileOperationJournal,
} from '../files/index';
export type {
  FileFingerprint,
  FileOperationFailure,
  FileOperationHooks,
  FileOperationJournal,
  FileOperationRecoveryResult,
  FileOperationResult,
  FileOperationStep,
  JournaledFileOperationOptions,
  JournaledFilesystemPort,
} from '../files/index';
export type {
  ExplorerDirectoryEntry,
  ExplorerFailure,
  ExplorerFilesystemPort,
  ExplorerGitDecoration,
  ExplorerGitDecorationPort,
  ExplorerGitState,
  ExplorerLoadState,
  ExplorerMetadata,
  ExplorerMetadataPort,
  ExplorerNavigationControllerOptions,
  ExplorerNode,
  ExplorerNodeKind,
  ExplorerOptions,
  ExplorerReadModel,
  ExplorerReadPort,
  ExplorerRoot,
  ExplorerVisibleRow,
  ExplorerWatchEvent,
} from '../files/index';

export {
  RealtimeSearchService,
  InMemorySearchBackend,
} from '../search/index';
export type {
  SearchRange,
  SearchMatch,
  SearchQuery,
  SearchFailure,
  SearchReadModel,
  SearchBackend,
  SearchBufferSource,
  SearchServiceOptions,
} from '../search/index';

export {
  NAVIGATION_CONTRACT_VERSION,
  FilePathIndex,
  FilePickerProvider,
  StaticPickerProvider,
  BoundedPickerModel,
  createNavigationContributionModule,
  truncatePathForDisplay,
} from '../navigation/index';
export { HostNavigationController } from '../navigation/host';
export type { HostLocation, HostNavigationFailure, HostNavigationProvider, HostNavigationResult } from '../navigation/host';
export type {
  PickerMode,
  PickerEntryKind,
  PickerEntry,
  PickerQueryRequest,
  PickerReadModel,
  PickerFailure,
  PickerProvider,
  PickerQueryOptions,
  WorkspaceRoot,
  IndexedPath,
  FilePathIndexOptions,
  FileIndexSnapshot,
  FileIndexFailure,
  FilePickerQueryOptions,
  FilePickerQueryResult,
  StaticPickerEntry,
  BoundedPickerModelOptions,
  NavigationContributionOptions,
} from '../navigation/index';

export {
  PersistenceService,
  createPersistenceService,
  decodeSession,
  encodeRecoveryCheckpoint,
  encodeSession,
  openFile,
  recoverFile,
  recoveryJournalPath,
  saveFile,
} from '../persistence/index';
export type {
  FileIdentity,
  OpenFileOptions,
  OpenedFile,
  PersistenceFailure,
  RecoveryCheckpoint,
  RecoveryOptions,
  RecoveryResult,
  SaveFileOptions,
  SaveFileResult,
  SessionDocumentState,
  SessionSnapshot,
} from '../persistence/index';
export {
  ConfigStore,
  compileConfig,
  compileInitialConfig,
  parseLanguageConfig,
  parseThemeConfig,
  parseToml,
  DEFAULT_COMMAND_CATALOG,
  DEFAULT_CONFIG_TOML,
  DEFAULT_LANGUAGES_TOML,
  DEFAULT_THEME_TOML,
  PERSONAL_MIGRATION_TOML,
} from '../config/index';
export type {
  AliasConfig,
  BindingConfig,
  CapturedConfigGeneration,
  CompiledConfig,
  ConfigCommandCatalog,
  ConfigCompileFailure,
  ConfigCompilerOptions,
  ConfigDiagnostic,
  ConfigLayer,
  ConfigProfile,
  EditorConfig,
  FormatterConfig,
  LanguageConfig,
  LanguageServerConfig,
  MouseConfig,
  ParsedToml,
  SearchConfig,
  ThemeConfig,
  TomlEntry,
  TomlParseFailure,
  TomlValue,
} from '../config/index';
export type {
  SyntaxDelta,
  SyntaxFailure,
  SyntaxFallback,
  SyntaxHighlightResult,
  SyntaxHighlightSpan,
  SyntaxHighlighterOptions,
  SyntaxParseRequest,
  SyntaxParseStats,
  SyntaxServiceDiagnostics,
  SyntaxSubmitResult,
  SyntaxTokenKind,
} from '../syntax/index';
